# This workflow runs for every push to master to lint and test the changes.
# If the checks are successful, the code is released as a new beta version.

name: Check & Release Beta

on:
  push:
    branches:
      - master

jobs:
  # NPM install is done in a separate job and cached to speed up the following jobs.
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            build
          key: node-modules-${{ github.run_id }}-v${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install

  lint:
    needs: [install]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Load Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            build
          key: node-modules-${{ github.run_id }}-v14
      - run: npm run lint


  test:
    needs: [install]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Load Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            build
          key: node-modules-${{ github.run_id }}-v${{ matrix.node-version }}
      - run: npm test

  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      -
        name: Load Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            build
          key: node-modules-${{ github.run_id }}-v${{ matrix.node-version }}
        # Check version consistency and increment pre-release version number.
      -
        name: Bump pre-release version
        run: node ./.github/scripts/before-beta-release.js
      -
        name: Publish to NPM
        run: NODE_AUTH_TOKEN=${{secrets.NPM_TOKEN}} npm publish --tag beta
      -
        name: Tag Version
        run: |
          git_tag=v`node -p "require('./package.json').version"`
          git tag $git_tag
          git push origin $git_tag
      -
        name: Read Versions For Images
        id: versions
        run: |
          apify=`cat ./package.json | jq '.version'`
          echo "::set-output name=apify::$apify"
          puppeteer=`cat ./package.json | jq '.optionalDependencies.puppeteer'`
          echo "::set-output name=puppeteer::$puppeteer"
      -
        name: Trigger Docker Image Build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TRIGGER_DOCKER_IMAGE_BUILD_TOKEN }}
          repository: apify/apify-actor-docker
          event-type: build-beta
          client-payload: '{ "apify_version": ${{ steps.versions.outputs.apify }}, "puppeteer_version": ${{ steps.versions.outputs.puppeteer }} }'
